"use client";
import { useState } from "react";
import { Footer, MarketingHeader } from "@/components/dexi";

const docs: Record<string, { title: string; copy: string; body: React.ReactNode }> = {
  OVERVIEW: { title: "BUILD WITH DEX-I.", copy: "Everything needed to understand the platform, its intelligence layer and its APIs.", body: <><p>DEX-I transforms existing CCTV and IP camera infrastructure into an intelligent monitoring system.</p><div className="doc-capabilities">{["PERSON DETECTION", "PERSON TRACKING", "MOVEMENT ANALYSIS", "SMART ZONES", "EVENT DETECTION", "REAL-TIME ALERTS", "SEARCHABLE EVENT HISTORY", "MULTI-CAMERA INTELLIGENCE", "BUSINESS ANALYTICS"].map((x) => <span key={x}>{x}</span>)}</div></> },
  "HOW DEX-I WORKS": { title: "FROM CAMERAS TO CONTEXT.", copy: "A direct path from existing infrastructure to decisions your people and systems can use.", body: <div className="doc-steps">{[["01", "CONNECT YOUR CAMERAS"], ["02", "DEFINE WHAT MATTERS"], ["03", "DEX-I WATCHES"], ["04", "EVENTS ARE DETECTED"], ["05", "INTELLIGENCE IS DELIVERED"]].map(([n, x]) => <div key={n}><span>{n}</span><strong>{x}</strong></div>)}</div> },
  CAPABILITIES: { title: "THE INTELLIGENCE LAYER.", copy: "From movement to meaning, DEX-I turns live video into structured signal.", body: <div className="doc-capabilities">{["PERSON DETECTION", "PERSON TRACKING", "SMART ZONES", "EVENT HISTORY", "REAL-TIME ALERTS", "BUSINESS ANALYTICS"].map((x) => <span key={x}>{x}</span>)}</div> },
  API: { title: "A CLEAR API SURFACE.", copy: "Connect DEX-I events to the systems your team already uses.", body: <><pre>{`GET /v1/events\n\n{\n  "event": "restricted_zone_entry",\n  "camera": "camera_04",\n  "timestamp": "2026-10-02T15:42:08",\n  "confidence": 0.94\n}`}</pre><div className="webhook-flow"><span>CAMERA</span><b>↓</b><span>DEX-I</span><b>↓</b><span>WEBHOOK</span><b>↓</b><span>APPLICATION</span></div></> },
  "ABOUT DEX-I": { title: "CAMERAS SHOULD DO MORE THAN RECORD.", copy: "DEX-I is an AI intelligence platform developed by DexLabs AI Education.", body: <><p>It transforms existing surveillance infrastructure into intelligent, actionable systems.</p><div className="equation"><span>COMPUTER VISION</span><b>+</b><span>REAL-TIME AI</span><b>+</b><span>BUSINESS INTELLIGENCE</span><b>=</b><strong>DEX-I</strong></div></> },
};
const nav = ["OVERVIEW", "HOW DEX-I WORKS", "CAPABILITIES", "SOLUTIONS", "API", "CAMERAS API", "EVENTS API", "ALERTS API", "ZONES API", "ANALYTICS API", "WEBHOOKS", "ABOUT DEX-I"];
export default function DocumentationPage() { const [active, setActive] = useState("OVERVIEW"); const current = docs[active] || { title: `${active}.`, copy: `Use the ${active.toLowerCase()} surface to connect DEX-I intelligence to your operation.`, body: <><p>Events are structured, searchable and ready to move into the systems your team already uses.</p><pre>{`GET /v1/${active.toLowerCase().replaceAll(" ", "-")}`}</pre></> }; return <div className="route-page route-dark docs-page"><MarketingHeader /><div className="docs-layout"><aside className="docs-sidebar"><p className="eyebrow">DOCUMENTATION</p><p className="docs-version">API VERSION / V1</p><nav>{nav.map((x) => <button className={active === x ? "active" : ""} key={x} onClick={() => setActive(x)}>{x}</button>)}</nav></aside><main className="docs-content"><div className="docs-topline"><span className="eyebrow">{active}</span><span className="docs-status">● ALL SYSTEMS DOCUMENTED</span></div><h1>{current.title}</h1><p className="route-lede">{current.copy}</p><div className="doc-body">{current.body}</div><div className="docs-next"><span className="eyebrow">NEXT STEP</span><strong>Connect a camera and send your first event.</strong><a className="button button-primary" href="/contact">TALK TO DEX-I <span>→</span></a></div></main></div><Footer /></div>; }
